// WhatCanICook Recipe Database - Phase 2A.2
// Expanded to 45 high-quality recipes with Cameroonian focus
// Each recipe has clear required vs optional ingredients for smart matching

export const RECIPES = [
  // ============ CAMEROONIAN SPECIALTIES ============

  // Eru Dishes
  {
    id: 'fufu-eru',
    name: 'Fufu & Eru',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'soup', 'leafy-greens'],
    description: 'Traditional Cameroonian dish with cassava fufu and spinach-based soup with meat.',
    requiredIngredients: ['cassava', 'eru', 'beef'],
    optionalIngredients: ['onion', 'tomato', 'crayfish', 'palm oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Boil cassava until soft and pound into fufu.',
      'In a pot, sauté onions and tomatoes in palm oil.',
      'Add beef and cook until browned.',
      'Add eru (leafy greens) and simmer with crayfish.',
      'Season and serve fufu with eru soup on the side.',
    ],
    prepTime: 45,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'garri-eru',
    name: 'Garri & Eru',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'cassava', 'leafy-greens'],
    description: 'Cassava granules with hearty leafy green soup.',
    requiredIngredients: ['garri', 'eru'],
    optionalIngredients: ['beef', 'onion', 'palm oil', 'crayfish', 'salt', 'pepper', 'water'],
    instructions: [
      'Mix garri with warm water to desired consistency.',
      'Prepare eru soup with beef, crayfish, and seasonings.',
      'Serve garri in a bowl with soup poured over.',
    ],
    prepTime: 30,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'water-fufu-eru',
    name: 'Water Fufu & Eru',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'cassava', 'leafy-greens'],
    description: 'Light cassava fufu prepared with water, paired with eru soup.',
    requiredIngredients: ['cassava', 'eru', 'water'],
    optionalIngredients: ['beef', 'onion', 'palm oil', 'crayfish', 'salt', 'pepper'],
    instructions: [
      'Grate and knead cassava with water repeatedly to make water fufu.',
      'Prepare eru soup with available ingredients.',
      'Serve together as a comforting meal.',
    ],
    prepTime: 40,
    difficulty: 'Medium',
    servings: 2,
  },

  // Ndolé Dishes
  {
    id: 'ndole-plantain',
    name: 'Ndolé with Plantain',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'leafy-greens', 'plantain'],
    description: 'Bitter leaf sauce with boiled plantain and meat.',
    requiredIngredients: ['ndole', 'plantain'],
    optionalIngredients: ['beef', 'shrimp', 'crayfish', 'palm oil', 'onion', 'tomato', 'salt', 'pepper'],
    instructions: [
      'Boil plantain until soft.',
      'Prepare ndole sauce with beef/shrimp, palm oil, and seasonings.',
      'Simmer until flavorful.',
      'Serve plantain with ndole sauce.',
    ],
    prepTime: 45,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'ndole-bobolo',
    name: 'Ndolé with Bobolo',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'leafy-greens', 'cassava'],
    description: 'Bitter leaf sauce served with cassava wrapped in leaves.',
    requiredIngredients: ['ndole', 'cassava'],
    optionalIngredients: ['beef', 'crayfish', 'palm oil', 'onion', 'salt', 'pepper', 'water'],
    instructions: [
      'Prepare bobolo by wrapping and boiling cassava paste.',
      'Make ndole sauce with available ingredients.',
      'Serve together.',
    ],
    prepTime: 50,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'ndole-rice',
    name: 'Ndolé with Rice',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'leafy-greens', 'rice'],
    description: 'Rich ndolé sauce served alongside fluffy white rice.',
    requiredIngredients: ['ndole', 'rice'],
    optionalIngredients: ['beef', 'crayfish', 'palm oil', 'onion', 'salt', 'pepper', 'water'],
    instructions: [
      'Prepare fluffy white rice in the usual way.',
      'Make ndole sauce with beef/crayfish and seasonings.',
      'Serve rice with ndole sauce on top.',
    ],
    prepTime: 40,
    difficulty: 'Medium',
    servings: 3,
  },

  // Achu
  {
    id: 'achu-yellow-soup',
    name: 'Achu with Yellow Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'cornmeal', 'soup'],
    description: 'Corn fufu served with aromatic yellow soup.',
    requiredIngredients: ['cornmeal', 'chicken'],
    optionalIngredients: ['palm oil', 'onion', 'tomato', 'crayfish', 'pepper', 'salt', 'water'],
    instructions: [
      'Prepare cornmeal fufu by boiling and pounding.',
      'Make yellow soup with chicken, palm oil, and spices.',
      'Serve fufu with soup.',
    ],
    prepTime: 40,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'achu-plain',
    name: 'Achu',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'cornmeal'],
    description: 'Traditional corn fufu, often served with soup or sauce.',
    requiredIngredients: ['cornmeal'],
    optionalIngredients: ['salt', 'water'],
    instructions: [
      'Boil water with salt.',
      'Gradually add cornmeal while stirring continuously.',
      'Cook until thick and smooth.',
      'Pound if possible for better texture.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },

  // Koki
  {
    id: 'koki-beans',
    name: 'Koki (Beans)',
    category: 'Cameroonian',
    tags: ['cameroonian', 'snack', 'beans'],
    description: 'Steamed bean pudding wrapped in leaves.',
    requiredIngredients: ['beans', 'cornmeal'],
    optionalIngredients: ['palm oil', 'onion', 'crayfish', 'salt', 'pepper'],
    instructions: [
      'Grind cooked beans and mix with cornmeal.',
      'Add palm oil, onion, and seasonings.',
      'Pour into leaf packets and steam.',
    ],
    prepTime: 45,
    difficulty: 'Medium',
    servings: 4,
  },
  {
    id: 'koki-corn',
    name: 'Koki (Corn)',
    category: 'Cameroonian',
    tags: ['cameroonian', 'snack', 'corn'],
    description: 'Steamed corn pudding, a favorite street food.',
    requiredIngredients: ['corn'],
    optionalIngredients: ['palm oil', 'crayfish', 'salt', 'pepper', 'onion'],
    instructions: [
      'Grind corn into paste.',
      'Mix with palm oil and seasonings.',
      'Wrap in leaves and steam until set.',
    ],
    prepTime: 40,
    difficulty: 'Medium',
    servings: 3,
  },

  // Soups & Sauces
  {
    id: 'pepper-soup-chicken',
    name: 'Chicken Pepper Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'chicken', 'spicy'],
    description: 'Aromatic broth with tender chicken and bold spices.',
    requiredIngredients: ['chicken', 'water'],
    optionalIngredients: ['ginger', 'garlic', 'pepper', 'onion', 'crayfish', 'salt', 'thyme'],
    instructions: [
      'Heat water and add chicken pieces.',
      'Add ginger, garlic, and spices.',
      'Simmer until chicken is cooked through.',
      'Serve hot with bread or rice.',
    ],
    prepTime: 30,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'pepper-soup-fish',
    name: 'Fish Pepper Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'fish', 'spicy'],
    description: 'Delicate pepper soup with fresh fish.',
    requiredIngredients: ['fish', 'water'],
    optionalIngredients: ['ginger', 'pepper', 'onion', 'crayfish', 'salt', 'garlic'],
    instructions: [
      'Heat water with ginger and spices.',
      'Add fish pieces and simmer gently.',
      'Season to taste and serve.',
    ],
    prepTime: 25,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'okra-soup',
    name: 'Okra Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'okra', 'vegetable'],
    description: 'Smooth, flavorful okra-based soup.',
    requiredIngredients: ['okra'],
    optionalIngredients: ['beef', 'fish', 'palm oil', 'onion', 'crayfish', 'salt', 'pepper', 'water'],
    instructions: [
      'Cook okra until tender.',
      'Pound or blend to desired smoothness.',
      'Add palm oil, meat/fish, and seasonings.',
      'Simmer and serve.',
    ],
    prepTime: 35,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'vegetable-soup',
    name: 'Vegetable Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'vegetable'],
    description: 'Hearty soup with mixed vegetables and protein.',
    requiredIngredients: ['water', 'vegetable'],
    optionalIngredients: ['beef', 'onion', 'tomato', 'carrot', 'potato', 'salt', 'pepper', 'palm oil'],
    instructions: [
      'Boil water and add beef if available.',
      'Add chopped vegetables and seasonings.',
      'Simmer until vegetables are tender.',
      'Serve hot.',
    ],
    prepTime: 30,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'groundnut-soup',
    name: 'Groundnut Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'groundnut', 'hearty'],
    description: 'Rich, creamy soup with groundnut base.',
    requiredIngredients: ['groundnut'],
    optionalIngredients: ['chicken', 'beef', 'onion', 'garlic', 'palm oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Grind groundnut into paste.',
      'Cook with water and meat.',
      'Add seasonings and simmer until thick.',
      'Adjust consistency as needed.',
    ],
    prepTime: 40,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'tomato-stew',
    name: 'Tomato Stew',
    category: 'Cameroonian',
    tags: ['cameroonian', 'sauce', 'tomato', 'main-meal'],
    description: 'Classic tomato-based stew with meat.',
    requiredIngredients: ['tomato', 'beef'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'pepper', 'salt', 'water'],
    instructions: [
      'Sauté onions and garlic in oil.',
      'Add tomatoes and cook down.',
      'Add beef and simmer until cooked.',
      'Season and serve with rice or fufu.',
    ],
    prepTime: 35,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'beans-stew',
    name: 'Beans Stew',
    category: 'Cameroonian',
    tags: ['cameroonian', 'sauce', 'beans', 'vegetarian'],
    description: 'Protein-rich stew with soft beans.',
    requiredIngredients: ['beans'],
    optionalIngredients: ['tomato', 'onion', 'oil', 'pepper', 'salt', 'water'],
    instructions: [
      'Boil beans until nearly soft.',
      'Sauté onions in oil.',
      'Add tomatoes and beans, then simmer.',
      'Season and thicken as desired.',
    ],
    prepTime: 50,
    difficulty: 'Easy',
    servings: 3,
  },

  // Fish Dishes
  {
    id: 'fish-stew',
    name: 'Fish Stew',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'fish'],
    description: 'Flavorful stew with fresh fish and tomatoes.',
    requiredIngredients: ['fish', 'tomato'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'pepper', 'salt', 'crayfish', 'water'],
    instructions: [
      'Sauté onions and garlic in oil.',
      'Add tomatoes and simmer.',
      'Add fish and cook gently until done.',
      'Season with salt, pepper, and crayfish.',
    ],
    prepTime: 30,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'fried-fish-plantain',
    name: 'Fried Fish with Plantain',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'fish', 'plantain'],
    description: 'Crispy fried fish served alongside golden fried plantain.',
    requiredIngredients: ['fish', 'plantain'],
    optionalIngredients: ['oil', 'salt', 'pepper', 'lemon'],
    instructions: [
      'Season and fry fish until crispy.',
      'Fry plantain slices until golden.',
      'Serve together with seasoning.',
    ],
    prepTime: 25,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'grilled-fish',
    name: 'Grilled Fish',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'fish', 'quick-meal'],
    description: 'Simply grilled fresh fish with herbs and spices.',
    requiredIngredients: ['fish'],
    optionalIngredients: ['lemon', 'garlic', 'pepper', 'salt', 'onion', 'oil'],
    instructions: [
      'Clean and season fish with lemon, garlic, salt and pepper.',
      'Grill on hot coals or stovetop until cooked through.',
      'Serve with sides of choice.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },

  // Chicken Dishes
  {
    id: 'poulet-dg',
    name: 'Poulet DG',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'chicken', 'festive'],
    description: 'Elegant chicken with creamy vegetable sauce (Director General style).',
    requiredIngredients: ['chicken'],
    optionalIngredients: ['carrot', 'potato', 'onion', 'garlic', 'cream', 'oil', 'salt', 'pepper', 'thyme'],
    instructions: [
      'Fry chicken pieces until golden.',
      'Sauté vegetables separately.',
      'Combine with cream and seasonings.',
      'Simmer until chicken is tender.',
    ],
    prepTime: 45,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'poulet-dg-plantain',
    name: 'Poulet DG with Plantain',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'chicken', 'plantain'],
    description: 'Poulet DG served with creamy fried plantain slices.',
    requiredIngredients: ['chicken', 'plantain'],
    optionalIngredients: ['carrot', 'potato', 'onion', 'cream', 'oil', 'salt', 'pepper'],
    instructions: [
      'Prepare poulet DG with sauce.',
      'Fry plantain until crispy.',
      'Serve together as a complete dish.',
    ],
    prepTime: 50,
    difficulty: 'Medium',
    servings: 3,
  },
  {
    id: 'chicken-stew',
    name: 'Chicken Stew',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'chicken'],
    description: 'Tender chicken in aromatic tomato-based sauce.',
    requiredIngredients: ['chicken', 'tomato'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'pepper', 'salt', 'water'],
    instructions: [
      'Brown chicken in oil.',
      'Add tomatoes, onions, and seasonings.',
      'Simmer until chicken is very tender.',
      'Serve with starch.',
    ],
    prepTime: 40,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'fried-chicken',
    name: 'Fried Chicken',
    category: 'Quick Meal',
    tags: ['quick-meal', 'chicken', 'fried'],
    description: 'Crispy, golden-brown fried chicken.',
    requiredIngredients: ['chicken'],
    optionalIngredients: ['oil', 'salt', 'pepper', 'garlic', 'paprika'],
    instructions: [
      'Season chicken pieces with salt and pepper.',
      'Heat oil in deep pan.',
      'Fry chicken until golden and cooked through.',
      'Drain on paper towels.',
    ],
    prepTime: 25,
    difficulty: 'Easy',
    servings: 3,
  },

  // Beef Dishes
  {
    id: 'beef-pepper-soup',
    name: 'Beef Pepper Soup',
    category: 'Cameroonian',
    tags: ['cameroonian', 'soup', 'beef', 'spicy'],
    description: 'Warming broth with tender beef and fiery spices.',
    requiredIngredients: ['beef', 'water'],
    optionalIngredients: ['ginger', 'pepper', 'onion', 'garlic', 'crayfish', 'salt', 'thyme'],
    instructions: [
      'Boil beef in seasoned water.',
      'Add ginger, pepper, and spices.',
      'Simmer until beef is tender.',
      'Serve hot.',
    ],
    prepTime: 45,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'beef-stew',
    name: 'Beef Stew',
    category: 'Cameroonian',
    tags: ['cameroonian', 'main-meal', 'beef'],
    description: 'Rich, slow-cooked beef in savory sauce.',
    requiredIngredients: ['beef', 'tomato'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'pepper', 'salt', 'water'],
    instructions: [
      'Brown beef pieces in oil.',
      'Add tomatoes and seasonings.',
      'Cover and simmer until very tender.',
      'Adjust thickness and serve.',
    ],
    prepTime: 60,
    difficulty: 'Easy',
    servings: 4,
  },

  // Plantain Dishes
  {
    id: 'fried-plantain',
    name: 'Fried Plantain',
    category: 'Snack',
    tags: ['snack', 'plantain', 'quick-meal'],
    description: 'Sweet, crispy fried plantain slices.',
    requiredIngredients: ['plantain'],
    optionalIngredients: ['oil', 'salt'],
    instructions: [
      'Peel and slice plantains.',
      'Heat oil in pan.',
      'Fry slices until golden and caramelized.',
      'Drain and season with salt.',
    ],
    prepTime: 15,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'boiled-plantain',
    name: 'Boiled Plantain',
    category: 'Side Dish',
    tags: ['side-dish', 'plantain', 'easy'],
    description: 'Soft, naturally sweet boiled plantain.',
    requiredIngredients: ['plantain'],
    optionalIngredients: ['water', 'salt'],
    instructions: [
      'Peel and cut plantains into chunks.',
      'Boil in salted water.',
      'Cook until soft, about 15-20 minutes.',
      'Serve hot.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'plantain-eggs',
    name: 'Plantain & Eggs',
    category: 'Breakfast',
    tags: ['breakfast', 'plantain', 'egg'],
    description: 'Fried plantain with scrambled or fried eggs.',
    requiredIngredients: ['plantain', 'egg'],
    optionalIngredients: ['oil', 'onion', 'salt', 'pepper'],
    instructions: [
      'Fry plantain slices until golden.',
      'In same or separate pan, cook eggs.',
      'Combine on a plate and serve.',
    ],
    prepTime: 15,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'plantain-porridge',
    name: 'Plantain Porridge',
    category: 'Breakfast',
    tags: ['breakfast', 'plantain', 'easy'],
    description: 'Soft, comforting plantain porridge.',
    requiredIngredients: ['plantain', 'water'],
    optionalIngredients: ['salt', 'oil', 'onion'],
    instructions: [
      'Peel and cut plantain into chunks.',
      'Boil in water until very soft.',
      'Mash or leave chunky as preferred.',
      'Season and serve.',
    ],
    prepTime: 25,
    difficulty: 'Easy',
    servings: 2,
  },

  // Rice Dishes
  {
    id: 'rice-beans',
    name: 'Rice & Beans',
    category: 'Main Meal',
    tags: ['main-meal', 'rice', 'beans', 'vegetarian'],
    description: 'Nutritious combination of rice and beans.',
    requiredIngredients: ['rice', 'beans'],
    optionalIngredients: ['tomato', 'onion', 'oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Boil beans until soft.',
      'Cook rice separately.',
      'Combine with sautéed onions and tomatoes.',
      'Season and serve.',
    ],
    prepTime: 50,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'jollof-rice',
    name: 'Jollof Rice',
    category: 'Main Meal',
    tags: ['main-meal', 'rice', 'festive'],
    description: 'Aromatic rice cooked in tomato sauce with spices.',
    requiredIngredients: ['rice', 'tomato'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'pepper', 'salt', 'water'],
    instructions: [
      'Blend tomatoes with onions.',
      'Cook in oil until sauce is rich.',
      'Add rice and water, cook covered.',
      'Season and serve.',
    ],
    prepTime: 35,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'tomato-rice',
    name: 'Tomato Rice',
    category: 'Main Meal',
    tags: ['main-meal', 'rice', 'tomato'],
    description: 'Flavorful rice with tomato and vegetables.',
    requiredIngredients: ['rice', 'tomato'],
    optionalIngredients: ['onion', 'oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Sauté onions in oil.',
      'Add tomatoes and cook down.',
      'Add rice and water.',
      'Cook covered until rice is done.',
    ],
    prepTime: 30,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'fried-rice',
    name: 'Fried Rice',
    category: 'Main Meal',
    tags: ['main-meal', 'rice', 'quick-meal'],
    description: 'Quick and tasty stir-fried rice with vegetables.',
    requiredIngredients: ['rice'],
    optionalIngredients: ['egg', 'carrot', 'onion', 'oil', 'salt', 'pepper'],
    instructions: [
      'Heat oil in wok or large pan.',
      'Add rice and stir-fry.',
      'Add vegetables and eggs.',
      'Combine and season.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 3,
  },

  // Potato Dishes
  {
    id: 'fried-potatoes',
    name: 'Fried Potatoes',
    category: 'Side Dish',
    tags: ['side-dish', 'potato', 'quick-meal'],
    description: 'Crispy golden fried potato pieces.',
    requiredIngredients: ['potato'],
    optionalIngredients: ['oil', 'salt', 'pepper', 'onion'],
    instructions: [
      'Peel and cut potatoes into pieces.',
      'Heat oil in pan.',
      'Fry until golden and crispy.',
      'Drain and season.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'potato-eggs',
    name: 'Potato & Eggs',
    category: 'Breakfast',
    tags: ['breakfast', 'potato', 'egg'],
    description: 'Hearty combination of potatoes and eggs.',
    requiredIngredients: ['potato', 'egg'],
    optionalIngredients: ['oil', 'onion', 'salt', 'pepper'],
    instructions: [
      'Fry potatoes until cooked.',
      'Cook eggs separately.',
      'Combine with seasonings.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'mashed-potatoes',
    name: 'Mashed Potatoes',
    category: 'Side Dish',
    tags: ['side-dish', 'potato', 'easy'],
    description: 'Smooth, creamy mashed potatoes.',
    requiredIngredients: ['potato'],
    optionalIngredients: ['oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Boil peeled potatoes until soft.',
      'Mash with oil and seasoning.',
      'Add water to reach desired consistency.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 3,
  },

  // Egg Dishes
  {
    id: 'omelette',
    name: 'Omelette',
    category: 'Breakfast',
    tags: ['breakfast', 'egg', 'quick-meal'],
    description: 'Simple fluffy omelette with light filling.',
    requiredIngredients: ['egg'],
    optionalIngredients: ['oil', 'onion', 'pepper', 'salt'],
    instructions: [
      'Beat eggs with salt.',
      'Heat oil in pan.',
      'Pour in eggs and cook until set.',
      'Fold and serve.',
    ],
    prepTime: 10,
    difficulty: 'Easy',
    servings: 1,
  },
  {
    id: 'tomato-omelette',
    name: 'Tomato Omelette',
    category: 'Breakfast',
    tags: ['breakfast', 'egg', 'tomato'],
    description: 'Omelette filled with tomato and spices.',
    requiredIngredients: ['egg', 'tomato'],
    optionalIngredients: ['oil', 'onion', 'salt', 'pepper'],
    instructions: [
      'Sauté tomato and onion.',
      'Pour beaten eggs over.',
      'Cook until set and serve.',
    ],
    prepTime: 12,
    difficulty: 'Easy',
    servings: 1,
  },
  {
    id: 'scrambled-eggs',
    name: 'Scrambled Eggs',
    category: 'Breakfast',
    tags: ['breakfast', 'egg', 'quick-meal'],
    description: 'Soft, fluffy scrambled eggs.',
    requiredIngredients: ['egg'],
    optionalIngredients: ['oil', 'salt', 'pepper', 'onion'],
    instructions: [
      'Heat oil in pan.',
      'Add beaten eggs.',
      'Stir constantly until cooked.',
      'Season and serve.',
    ],
    prepTime: 10,
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: 'fried-eggs',
    name: 'Fried Eggs',
    category: 'Breakfast',
    tags: ['breakfast', 'egg', 'quick-meal'],
    description: 'Simple fried eggs with crispy edges.',
    requiredIngredients: ['egg'],
    optionalIngredients: ['oil', 'salt', 'pepper'],
    instructions: [
      'Heat oil in pan.',
      'Break eggs into pan.',
      'Cook until whites are set.',
      'Season and serve.',
    ],
    prepTime: 8,
    difficulty: 'Easy',
    servings: 1,
  },
  {
    id: 'boiled-eggs',
    name: 'Boiled Eggs',
    category: 'Breakfast',
    tags: ['breakfast', 'egg', 'quick-meal'],
    description: 'Simple boiled eggs, soft or hard.',
    requiredIngredients: ['egg', 'water'],
    optionalIngredients: ['salt'],
    instructions: [
      'Boil water.',
      'Add eggs.',
      'Boil for 5-10 minutes depending on preference.',
      'Cool and peel.',
    ],
    prepTime: 15,
    difficulty: 'Easy',
    servings: 2,
  },

  // Pasta
  {
    id: 'spaghetti-tomato-sauce',
    name: 'Spaghetti with Tomato Sauce',
    category: 'Main Meal',
    tags: ['main-meal', 'pasta', 'tomato'],
    description: 'Classic spaghetti with rich tomato sauce.',
    requiredIngredients: ['spaghetti', 'tomato'],
    optionalIngredients: ['onion', 'garlic', 'oil', 'salt', 'pepper', 'water'],
    instructions: [
      'Cook spaghetti in boiling salted water.',
      'Make sauce: sauté onions, add tomato, simmer.',
      'Drain pasta and combine with sauce.',
    ],
    prepTime: 25,
    difficulty: 'Easy',
    servings: 3,
  },
  {
    id: 'spaghetti-eggs',
    name: 'Spaghetti with Eggs',
    category: 'Main Meal',
    tags: ['main-meal', 'pasta', 'egg'],
    description: 'Spaghetti tossed with scrambled eggs.',
    requiredIngredients: ['spaghetti', 'egg'],
    optionalIngredients: ['onion', 'oil', 'salt', 'pepper'],
    instructions: [
      'Cook spaghetti in boiling water.',
      'Sauté onions in oil.',
      'Add beaten eggs and scramble.',
      'Combine with drained pasta.',
    ],
    prepTime: 20,
    difficulty: 'Easy',
    servings: 2,
  },

  // Snacks & Other
  {
    id: 'pancakes',
    name: 'Pancakes',
    category: 'Breakfast',
    tags: ['breakfast', 'snack', 'easy'],
    description: 'Fluffy pancakes, good for breakfast.',
    requiredIngredients: ['flour', 'egg'],
    optionalIngredients: ['salt', 'water', 'oil'],
    instructions: [
      'Mix flour, egg, salt, and water to make batter.',
      'Heat oil in pan.',
      'Pour batter and cook until golden.',
      'Flip and cook other side.',
    ],
    prepTime: 15,
    difficulty: 'Easy',
    servings: 2,
  },
];
